### ISSUE TITLE
Ästhetische Bedenken

### ISSUE THREAD

**Issue by sjmielke** [fsr/ese-webseite#11]
*rant incoming*

Das Design wirkt generell irgendwie alles so zusammengewürfelt und weder übersichtlich noch schön.
Mal im Vergleich: Die alte Seite wirkt son bisschen alt, das stimmt und da flackern gar keine fancy Javascript-CSS-Animationen, von mir aus, aber die ist einfach trotzdem noch deutlich aufgeräumter und übersichtlicher - mal von Dingen abgesehen, wie dass das ESE Logo rechts nicht so kleine oben irgendwo rumschwirrt sondern ja irgendwie sauber über dem Menü sitzt, liegt nicht überall irgendein Mist rum wie diese "Jul 20, 2015 \n ESE 2015" Zeilen (aber die meinte Justus gerade schon, dass er sie rauspatcht)

Auf der neuen Seite muss man jetzt außerdem erst ewig über den übergroßen Monsterslider, Textblöcke und Kästchen scrollen bis man tatsächlich einen Zeitplan findet - der war auf der alten Seite präsenter und das nicht nur, weil die Schrift kleiner war (auch wenn ich auch da nicht verstehe, warum die neue Seite zu viel dünner und so elendig whitespacig in die Länge gezogen sein muss - ich dachte Monitore sind von 4:3 aus vorrangig breiter geworden und nicht unbedingt länger? und nur weil das mobil besser sein mag, muss man doch nicht die PC-Version (die vermutlich 90% der Leute in den nächsten Wochen nutzen werden) auch so verkrüppeln). Ich finde das irgendwie echt schlimm, dass ich auf meinem ja nun wirklcih nicht allzu schlecht auflösenden Laptopmonitor genau eine Zeile des Haupttextes sehe, wenn ich die Seite ansurfe, weil der Rest weiter unten verborgen ist. Aber Justus meinte schon, dass nicht jeder so auf kompakte Textwände steht und etwas mehr Platz zwischen den Zeilen für die Lesbarkeit gut tut (was für längere Fließtexte sicher nicht falsch ist, aber für die paar Texte hier finde ich es eher nervig, gerade da man die nur einmal liest, den Rest der Seite, also bspw. den Zeitplan aber sehr viel häufiger suchen wird).

Soviel zu meiner genervten Meinung, Lars kann dir im Zweifelsfall sicher bestätigen, dass ich von echtem Design keine Ahnung habe, aber ich finde die Seite so halt echt noch nicht in Ordnung.

Ich würde deshalb zumindest in Erwägung ziehen, den Slider ein gutes Stück kürzer zu machen und dann rechts das ESE-Logo wieder größer, das ist so schon ein bisschen klein, und dann sind Menü und der gerade völlig sinnlose kleine Balken rechts unter dem Karlchen vielleicht wieder auf einer Höhe und es wirkt alles garnicht mehr so furchtbar (obwohl ich befürchte, dass das so wie die Seite aufgebaut ist nicht exakt funktionieren kann, weil die erste Aufteilung horizontal ist und nicht vertikal...). Und/oder ihr dreht mal die (Schrift-)größe ein gutes Stück runter, so zwei Stufen rausgezoomt finde ich das alles schon erträglicher, da ist mir dann nur noch die Seite als Ganzes zu dünn. :)

**Comment by MarauderXtreme** [comment]
1. If you want the font-size to be smaller be so kind and configure your browser correct. The font-size gets set by your browser so that everyone can use his own preference. (Normally browser set 16px so it is not really the "mobile-optimization" you are blaming)
2. If you want to have a smaller slider would you kindly provide correctly cropped images. I have to admit I can not handle graphic programms well. I would be delighted to get the correctly cropped images.
3. I agree with the logo. I will adress this in a commit later.
4. The vertical layout is so far the best solution for a mobile version. It was a requirement to develop a mobile layout but we had no feedback after we did so. It is a grid layout so feel free to provide a better solution. Even a simple sketch could help us.
5. As you said this bar is quite useless. I would recommend to delete it and provide a ready made image for this block.

I dislike the idea of setting the fontsize in px and not relative because many people enjoy seeing their own settings on a website. A friend of mine always uses a super large font-size and so it would adapt his own needs.

**Comment by MarauderXtreme** [comment]
I updated the markup.    
We can still change the layout to 8 - 4 .Than the complete sidebar gets a bit wider but I don't know if this is a good idea.

**Comment by sjmielke** [comment]
> configure your browser correct

Didn't know about this, cool idea. Unfortunately absolutely not working for the text on the website - or at least neither in Firefox nor Chrome on my machine (plus other websites choose a much more sensible font size when I keep the default of 16 than when I change it. The mixture of fixed and browser-depending font sizes makes everything shitty with a custom font size anyway, I'm afraid).

> provide correctly cropped images

I guess the website designer should decide what correctly means here. I already heard the thing about the images from Justus too. But come on, cropping images...

> The vertical layout is so far the best solution for a mobile version
> feel free to provide a better solution

Agreed, also I dont really have any better idea. Just thought maybe you know of some awesome trick that I don't know :)

> As you said this bar is quite useless. I would recommend to delete it...

Sounds good :)

> ...and provide a ready made image for this block.

Wait what? Why not just let the sidebar begin under the logo itself? Effectively a display:none for the "column sidebar-header small-12" div is what I'd love to see, dunno how that div is generated behind the scenes.

**Comment by MarauderXtreme** [comment]
> some awesome trick [for logo]
Foundation provides this handy little tool called [Equalizer](http://foundation.zurb.com/docs/components/equalizer.html). I already suggested the use of it to @JustusAdam but he disliked it because it is mainly JS. I see his point and with the current layout configuring the equalizer would not work.
> Sounds good
We were told to try to match up the new layout to the old one. So we included it although it bothered me a bit. But since you are the only one until now providing some feedback to the design I will stick with your suggestion.
> display:none
Ah no. Since we have nearly plain HTML we can easily kick out the div. I think I will do it later.
> not working for the text on the website
You are right I'm sorry. I did not notice it until now. I've searched through the SCSS and found that someone hard set the value in a non "Foundation" way. I think I will try to fix it later too.

**Comment by sjmielke** [comment]
Okay, yeah about the feedback I can definitely see what you mean, but in all honesty the site did not look ready for feedback to me - perhaps next time just provoke some people on the mailing list what they think about the design - everybody has an opinion on that :D

(oh and yeah, I agree with whatever Justus said about disliking that that is JS :P)

Looking forward to see how it looks then.

**Comment by MarauderXtreme** [comment]
Well since I am only on the website mailinglist I cannot really provoke feedback. (At least I think Justus, Philipp and me are the only one on this list)     
We had finished all functionality or had issues to track the progress on them. I thought we would first get feedback or a list with things to do from @heisig since he is the one in charge.
Now this gets a bit sporty because I have to work again and the launch should take place as soon as possible.

**Comment by MarauderXtreme** [comment]
Is there still something to fix? At least my browser does everything correct.

**Comment by heisig** [comment]
Ich bin gerade dran ein bisschen was zu stylen. Betrifft ein paar Kleinigkeiten welche dann hoffentlich die Seite etwas stimmiger aussehen lassen.

**Comment by MarauderXtreme** [comment]
Please make sure that you do it the foundation way. ^^ Maybe you can use some SCSS variables so it will be easier to handle.

**Comment by heisig** [comment]
Ja mache ich soweit es mir möglich ist. Ist gerade etwas schwierig immer die richtigen Stellen zu finden aber ich achte darauf, dass ich nicht einfach nur CSS überschreibe.

**Comment by MarauderXtreme** [comment]
You can find all variables under _settings.scss. These should be overridden in _vars.scss with our custom values. All other none modular styles go into _custom.scss.

**Comment by heisig** [comment]
Ah ok, danke. Dann packe ich die mal in _vars.scss.

**Comment by heisig** [comment]
Ich hoffe mal, dass ich alles soweit an die richtigen Stellen gemacht habe. Manches ist sicher nicht so optimal gelungen, aber es war oft auch recht schwer die Dinge anzupassen.

Btw: Die Headerfarbe sehe ich auch noch kritisch. Vielleicht ändern wir sie wieder auf ein dunkles Grau, aber mal sehen wie es wirkt.

**Comment by MarauderXtreme** [comment]
Okay. So I think we can close this issue and continue discussion in another if there will be a problem.
