### ISSUE TITLE
Out-of-date favicon used

### ISSUE THREAD

**Issue by jgonsior** [fsr/ese-webseite#14]
It looks like https://ese.ifsr.de/favicon.ico is used as the favicon for https://ese.ifsr.de/2015 - maybe you can include https://www.ifsr.de/lib/tpl/dokuwiki-fsr2014/images/favicon.ico to fix this?

**Comment by MarauderXtreme** [comment]
What the hell? Since when is this site live? It even isn't the version from the repository?
I can only include it to this repo but not into the other version.

**Comment by jgonsior** [comment]
The version that is live is an emergency solution created by @heisig

**Comment by MarauderXtreme** [comment]
Oh cool. Great that no one participiating in this project was informed about this. So what is this now? Can we just throw away out complete work?

Instead of deploying this shitty whatever how about helping to bring the correct version online? @heisig

**Comment by heisig** [comment]
Hör bitte mal auf so krass zu ranten bitte..

Ich habe gestern das Teil zusammengehauen, damit wir zumindest etwas haben was die Erstis informiert bis die Webseite fertig ist (klar bin ich Schuld daran, dass die Webseiten-Geschichte dieses Jahr so verzögert ist und es tut mir auch leid). Es gingen auf unserer FSR-Mailingliste (auf der du halt nicht bist) mehrere Mails zur Webseite hin und her und gewisse Personen wollte den Zeitplan schon auf eigene Faust online bringen (sei es als Bild aus der No Panic oder als HTML Tabelle). Meine Option ist da noch richtig gut!

Ein shitty whatever ist es aber eher nicht. Das ist halt deine Meinung.

Und das wir die komplette Arbeit nun wegwerfen habe ich niemals gesagt. Ich möchte, dass wir (ich halt jetzt auch verstärkt) die Webseite nun mit den neuen Technologien fertig machen und dann die "Notlösung" ersetzen.

Ok?

**Comment by MarauderXtreme** [comment]
At least you could have informed us(me) so that I don't end up in such a mood like I now have. We have this mailinglist for the website group.    
Well I agree that this is better than a picture but well ...    
I hope we will finish this soon since I created a milestone for today that should be the launch date. I did this to get a bit attention to this project which seemed to have worked. (Maybe it was the communication on the mailinglist and not this)    
To explain my rant. I just sat down in my holidays and put a lot of effort into this together with @JustusAdam . Than it seemed that everything was fine or no one cared about it. So I hoped and waited for input to finish it. Now I see something live that is not my work. See what I mean?

**Comment by heisig** [comment]
Ich habe zumindest Justus und den FSR informiert. Dich leider nicht, hätte ich machen sollen..

Was du jetzt so schlimm an der Seite findest musst du mir dann mal bei Zeiten erzählen.

Um die ganze Diskussion abzukürzen: ja ich hoffe auch, dass die Seite in den nächsten Tagen dann komplett fertig wird und werde mit daran arbeiten.
