### ISSUE TITLE
Correcting HTML errors

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#17]
Because browser are very kind and HTML is a quite picky markup, we won't see some of the obvious errors. I checked it with the [Validator](https://validator.w3.org/nu/?doc=http%3A%2F%2Ffsr.github.io%2Fese-webseite%2F) and found some issues that should be adressed.

* alt attributes
* rowspan . issues
* width in table

The only thing that can be left out is the problem with the src in the slider because this is not a bug rather a feature. ^^

**Comment by sjmielke** [comment]
Also: what the hell is up with the *insane* number of newlines, empty lines and lines with random amounts of whitespace in the generated HTML code? It is practically non-readable!

**Comment by MarauderXtreme** [comment]
I think this is a problem with the jekyll generator. I seems that it is just stripping the template commends and replaces them with empty lines and spaces.

**Comment by JustusAdam** [comment]
@sjmielke Excuse me for making the code readable. This is as a result of readable and modular liquid templates. Why would you care about newlines in the output HTML? Here's hardly any need to look at the generated html and no reader, crawler, validator or browser cares for newlines? Why is that suddenly an issue?

**Comment by sjmielke** [comment]
Still nothing unfixable, see the first few results that pop up if you search for this problem.
And I really cannot believe that I am the only one who regularly looks at the code of a website - especially when we try to launch an overdue project full of open questions and criticism.

Also consider the following:
```
$ grep -v "^\s*$" fsr.github.io.htm > stripped.htm
$ ls -la *.htm
-rw-r--r-- 1 sjm sjm  12595 Sep 20 19:01 ESE 2014 | Wann.htm
-rw-r--r-- 1 sjm sjm 197376 Sep 20 19:01 fsr.github.io.htm
-rw-r--r-- 1 sjm sjm  39001 Sep 20 19:03 stripped.htm
```
Whitespace, if it is present in such an immense quantity has a very noticeable effect.

(By the way: does anybody still remember that sports club website or something, made with MS Frontpage I think, which contained this huge number of newlines in the astonishingly long code? And how ridiculous it was? Yeah.)

**Comment by JustusAdam** [comment]
Well then fix it, if is concerns you so damn much. But don't come crying to me in a year, because we have a giant blob of unmaintainable code.

**Comment by kiliankoe** [comment]
Holy crap, I thought @sjmielke was kidding about the whitespace. That has nothing to do with readable or maintainable code, it is (not even kidding) just *shit*. Not talking about your work, but whatever is causing that *has* to go. 

> Excuse me for making the code readable.

Ha.

**Comment by sjmielke** [comment]
It's a bit of a tricky issue and honestly the most ridiculous thing here is probably how liquid can take itself seriously while not doing anything about this in *years*.
So for the time being this seems like the best way to go: http://jch.penibelst.de/ (You might try to include this layout as it is or at least adapt some of the code used there maybe?)
Or you use a simple plugin that runs the equivalent of the grep-expression above (exists as well) - not being able to run it on gh-pages is very annoying, but, hey, better than nothing.
Otherwise our "deployment procedure" will just have the include this grep-writing-mess for our html files. Yay.

**Comment by JustusAdam** [comment]
All right boys, since this is apparently by far the most important issue to fix right now, knock yourself out.

It's not like you could be doing useful things like writing the page content or help translating it.

No, instead it is obviously the best choice to pick out a stylistic issue, which impacts the site in an almost not measurable way and then insult the people that have created the page and put thought and work into it for months. 

@kiliankoe You are not Torvalds, you don't get to act like him, especially if you're not the one in charge for the project in question.

**Comment by kiliankoe** [comment]
Even Torvalds doesn't get to act like the douchebag he usually comes across as. But thanks for the comparison nonetheless.

What I'm saying is that iregardless of the amount of work you guys have poured into this (which I never meant to disrespect), that HTML output is not tolerable for the final product. A workaround like what @sjmielke said has to be incorporated. It can't be that moving from a little static HTML project to a system like this (as nice as it may be) will produce such excruciatingly ugly output.

**Comment by MarauderXtreme** [comment]
I think the whitespace problem should be an issue to solve later. Since this does not impact the delivery of the website much we can deal with it later. Possibly some of this can be resolved by configuring the webserver with the right compression and caching settings.

For now we should deal with the "serious" HTML errors that were the initial topic of this issue.

**Comment by MarauderXtreme** [comment]
4c1fafa2933d30d6f8699eea375782b8c60e1c5c contains the fix for the . issue for rowspan.

**Comment by MarauderXtreme** [comment]
With this only the alt attribute problem is left.

**Comment by MarauderXtreme** [comment]
With f975f85345c4b8318587f7834c4b0a209fc2805c I finally manged to get rid of all validator errors.

**Comment by JustusAdam** [comment]
Thank you for doing all this.

**Comment by MarauderXtreme** [comment]
Yeah. It bothered me and I wanted them fixed.
