### ISSUE TITLE
Stundenpläne

### ISSUE THREAD

**Issue by heisig** [fsr/ese-webseite#28]
Die Stundenpläne sind mittlerweile angekommen. Es gibt zwar noch ein paar Dinge die geklärt bzw. angepasst werden müssen, aber am Montag sollten die Stundenpläne bestenfalls auch auf  der Webseite zu finden sein.

Wir haben die Pläne zwar in HTML vorliegen aber das ist ganz ganz hässliches Zeug. Wollen und können wir da die gleiche Technik vom Ablaufplan nehmen?

**Comment by JustusAdam** [comment]
theoretisch ja

**Comment by JustusAdam** [comment]
I have a crude implementation for automatic generation ready. We'll have to fix the styling though.

**Comment by sjmielke** [comment]
In either case, don't forget that https://github.com/fsr/stundenplaene exists, might be useful.

As I already said to @heisig, I think we should finally give up on trying to write and test a new parser every goddamn year. My idea: write a tool that 1) generates an empty TSV file with weekday and timeslot "headers" for 15 empty tables (which you can then easily fill in a nice graphical tool like LibreOffice Calc) and 2) parses this filled-out TSV (which is trivial) into some representation that can then be used by the haskell renderer from last year or the whatever-it-is-renderer from this year :)
The tool would likely consist of <50 lines $arbitrary_language and filling out a few tables is definitely less work than rewriting or adapting the parser.

**Comment by JustusAdam** [comment]
Yeah .. lets use the awesome tool with zero documentation ... What kind of output does this thing produce?

**Comment by sjmielke** [comment]
I never said it was awesome :P It parses the TUD HTML into the (self-explanatory) data structures (a list of plans is [(String, [Day])] ), applies some changes to them (math tutoriums and so on) and then pushes them through an inline hamlet template to generate nicer html plans - the ones you can see on the v2014 version of the site.
I thinkt the rendering/template could be reused, but feel free to rewrite everything to play nice with the new website. Otherwise I would try to get to write the tool I hinted at above, so if you can parse simple TSVs in your rendering engine, that would work too. Or you write that one as well.

Then again, in the worst case we could even the use HTML we got this year as it is - it's not as bad as the last years and with some simple string replacement operations it might be... at least usable.

**Comment by JustusAdam** [comment]
Well, I would have preferred if it'd just create some Haskell data structures that I could serialise using the yaml library. That would have been easy.

This works best if you have custom data structures or `newtype`s.

**Comment by MarauderXtreme** [comment]
Outdated. Will open new issue when necessary this year.
